/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TemplateInputs } from "./templateinputs";
import { Expose, Type } from "class-transformer";

export class Template extends SpeakeasyBase {
  /**
   * The template's description.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "description" })
  description?: string;

  /**
   * The template's unique identifier.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  @SpeakeasyMetadata({ elemType: TemplateInputs })
  @Expose({ name: "inputSchema" })
  @Type(() => TemplateInputs)
  inputSchema?: TemplateInputs[];

  /**
   * The template's name.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;
}
