/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Template } from "./template";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class TemplateOutput extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: Template })
    @Expose({ name: "data" })
    @Type(() => Template)
    data?: Template[];

    @SpeakeasyMetadata()
    @Expose({ name: "requestId" })
    requestId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "resource" })
    resource?: string;
}
